version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - doxygen
  commands:
    - ls
    - cd docs/ &&
      pip install -r requirements.txt &&
      doxygen && make html
    - cp -r docs/build/html/* _readthedocs/html/
